name: mop
description: A Finogeeks MiniProgram Flutter SDK.
version: '2.44.9'
homepage: https://github.com/finogeeks/mop-flutter-sdk

environment:
  sdk: ">=2.19.2 <3.0.0"
  flutter: ">=3.7.4"
#environment:
#  sdk: '>=2.12.0 <3.0.0'
#  flutter: '>=2.2.3'

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.finogeeks.mop
        pluginClass: MopPlugin
      ios:
        pluginClass: MopPlugin
